### ISSUE TITLE
add paste source citation icon to the INDI names

### ISSUE THREAD

**Issue by HerzScheisse** [Jefferson49/RepositoryHierarchy#51]
Hi,

thanks for this awesome module and all its great features.

is it possible to add the "paste source citation" icon to the names aswell?
![repo_paste_source](https://github.com/Jefferson49/RepositoryHierarchy/assets/146635896/5345ba39-4552-4fe0-89fe-0e7ac8dd7660)

thanks
/Holger

**Comment by Jefferson49** [comment]
Hello Holger,

thank you for reporting the issue. 

For simplification, I wanted to use the copy/paste mechanism only for facts/events, because all facts/events use the same code to view and edit.

However, after checking your issue, I recognized that the **copy** icon is shown for source citations within NAME, but the **paste** icon cannot be used. This is really inconsistent.

![copy paste source citations in INDI-NAME](https://github.com/Jefferson49/RepositoryHierarchy/assets/81484983/197ed3b9-a4fa-4da3-949b-ae8a78eac6bb)

The reason is that a source citation within NAME is shown with the same code like within other facts/events. Therefore, the copy icon is shown (although not intended). However, the name data itself is shown with another piece of webtrees code, which is different from facts/events. Therefore, the paste icon is not shown here. 

I have to think about this issue and will check how much effort it is to add the paste icon to NAME also.

**Comment by HerzScheisse** [comment]
yeah i noticed that...

no worries... its not that urgent...
at the moment i'm still using raw gedcom to add source citations, as i have been using since my start with webtrees...

only the missing paste ability for the name fields stop me from using this function in general...

**Comment by Jefferson49** [comment]
I was able to include the paste mechanism into NAME. However, there is an issue with vesta. If using vesta in parallel, the paste icon is not shown. The reason is that vesta modifies the NAME view also and the two modifications will not be combined. From your screenshot, I assume that you are using vesta.

Without vesta it looks like this:

![paste icon NAME](https://github.com/Jefferson49/RepositoryHierarchy/assets/81484983/e8ee4d3d-92ea-4833-b6d8-bb72389c3773)

If you want to test the paste mechanism in NAME, you can install the attached module, which is version v1.38 plus the paste mechanism in NAME:

[repository_hierarchy_v1.3.8_f16987b2.zip](https://github.com/Jefferson49/RepositoryHierarchy/files/14130887/repository_hierarchy_v1.3.8_f16987b2.zip)

**Comment by HerzScheisse** [comment]
thanks for the addition... :)

**Comment by ric2016** [comment]
Ideally there would be another sub-view in webtrees just for the edit controls of a name. Based on past experience I do not think such a feature request would be accepted though.

I'll expand the Vesta configuration options instead.

**Comment by Jefferson49** [comment]
> I'll expand the Vesta configuration options instead.

Hallo Richard,

thank you very much for supporting this issue! I agree that we should not create dependencies between the custom modules. I think that the option in vesta is a good approach.

**Comment by HerzScheisse** [comment]
wow that was a fast fix... thank both of you for your changes :)
