### ISSUE TITLE
Repository not translated

### ISSUE THREAD

**Issue by HerzScheisse** [Jefferson49/RepositoryHierarchy#52]
Hey @Jefferson49 

Dont know if its just me... do you have the latest vesta modules and your updated release (posted in a prev. issue) installed?

I noticed that the Repository is not translated anymore... 

![2024-02-09 23_52_33-August Uridat 1821–1890 – Familienforschung eisold family - Brave](https://github.com/Jefferson49/RepositoryHierarchy/assets/146635896/1fe38f0c-e281-4414-8626-52ece6ba54f8)

It's in line 60 of repository_hierarchy\resources\views\source-facts-within-citation.phtml

If I update that to "Source" it gets translated... but not the "Repository" even if i update that function to `I18N::translate(`
I also tried to manually add it to the de.mo/de.po files

So i wonder if I broke that translation somewhere else... been researching this for an hour now, and cant find a solution...

Could you please check if it works in your setup?

Thanks
Holger

**Comment by Jefferson49** [comment]
Hello Holger,

I cannot reproduce this issue in my installation. `MoreI18N` is a class from vesta, which I copied as a library to my module. The idea of `MoreI18N` is that translations, which are already available in the webtrees are reused in the custom module and do not have to be translated once again.

Therefore, `MoreI18N::xlate('Repository')` should deliver the original webtrees translation. Can you check if 'Repository' translated in other webtrees views?

If replacing `MoreI18N::xlate('Repository')` by `I18N::translate('Repository')`, the custom module will try to translate with the custom module .po/.mo files. This will not work, since 'Repository' is not part of the .po files. However, if you add a translation for 'Repository' to the .po file, it should work.

It is difficult for me to find an explanation.

I will publish a new version of the module this weekend. You can try to check with the latest code (zip file in attachement), Maybe, it would help to delete your existing 'repository_hierarchy' folder before copying the new code to your 'module_v4' folder.

[repository_hierarchy_v1.3.8_10fdef73.zip](https://github.com/Jefferson49/RepositoryHierarchy/files/14228361/repository_hierarchy_v1.3.8_10fdef73.zip)

**Comment by HerzScheisse** [comment]
thanks for investigating... I've now found my issue... it comes from a translation that i did on my own -.- its in the https://github.com/06Games/Webtrees-MailSystem/blob/main/resources/lang/de.po 

i did found this while i was disabling each module by its own which i lastly changed...

need to provide a change for that module...

thanks for your help
