### ISSUE TITLE
No delete and sort icon if same source twice

### ISSUE THREAD

**Issue by HerzScheisse** [Jefferson49/RepositoryHierarchy#55]
Hey Jefferson49,

I've noticed another little problem and while thinking of a fix it might be not an easy one to solve, to not delete both sources of the same type...

![2024-02-19 18_25_20-Johann Georg Popp 1673–1742 – Familienforschung eisold family - Brave](https://github.com/Jefferson49/RepositoryHierarchy/assets/146635896/49a5f08d-0744-4176-84eb-6b7f6a5d5a08)
in this picture you see that there on some source no delete and sort icons...

but also for the first appearance of Wohnsitz... why cant i delete this source? is it because I recently copied this one and its in the cache?

I could easily fix this in the raw gedcom, but i left this untouched for now, just in case you want see and check it yourself... if so, please let me know and hit me up at github@eisold.family  

[edit] sorry i didnt looked carefull enough... it was not caused by doubled sources... so i deleted that part here...

**Comment by Jefferson49** [comment]
First of all, I really like the way you make use of sources/citations! 

It is very interesting that you ran into the described issue. The behavior is intended, because I could not find a good solution for some situations. The reason is that webtrees uses the same view for all facts and when the view is called, only a very limited information is handed over to the view file.

You can see in the [code](https://github.com/Jefferson49/RepositoryHierarchy/blob/main/resources/views/fact-gedcom-fields.phtml#L20) that  only the following parameters are handed over to the view:
- A gedcom string (e.g. "2 SOUR @X10787@ 3 PAGE Seite 17")
- The parent tag (e.g. "INDI:BIRT:DATE")
- The tree 


With this (limited) available information, I can not differenciate if the same source citation (is used several time within an individual (or family) with the same parent tags (INDI:PROP in the example below).

**Example GEDCOM:**
0 @I9803@ INDI
1 PROP Acker
2 SOUR @S10787@
3 PAGE Seite 17
1 PROP Haus
2 SOUR @S10787@
3 PAGE Seite 17

Since I cannot distinguish between the two source citations, I cannot delete one of them, because I **might get the wrong one**.

I thought that this situation rarely happens and decided not to show the delete and the move icons in this case. Now, I learned that these situations do not seem so rare :-)

I am just wondering wether I should change the behvaior and show the delete/move icons even in these situations. If delete/move is selected, I could show a warning message and describe that no action can be taken. These source citations need to be deleted/moved with the regular webtrees features.

What do you think about such an approach with warning messages? Or do you have some other good proposal?

**Comment by HerzScheisse** [comment]
Thank you for your response and explanations...

I'm using this style of sources and citations since i started using Family Tree Maker years ago... Because at some point i ran into problems, where i didnt know where a fact came from and needed to review all linked sources... so i can easily find the related source very easily...
I do this for each different fact, event, name, variation of names....

Regarding my issue... as i edited my last message, first i thought it was due to doubled sources/citaions... but its not... (i was not paying much attention while writing my first draft for the issue)
f.e. the first appearance of Beruf with the 3 Sources, each of them is a different one... 

the Gedcom looks like this:
`1 OCCU Fleischhacker
2 DATE ABT 1700
2 PLAC Stockenroth, Hof, Bayern, Deutschland
2 SOUR @S44@
3 PAGE 1700 - Bild 199 - Nr. 3 - https://www.archion.de/p/39e16d13c3/
3 OBJE @M896@
2 SOUR @S8@
3 PAGE 1761 - Bild 89 - Nr. 3 - https://www.archion.de/p/87bcb30dfb/
3 OBJE @M944@
2 SOUR @S44@
3 PAGE 1701 - Bild 270 - Nr. 3 - https://www.archion.de/p/cfa46769d4/
3 OBJE @M1311@`

While I understood your explanation of the issue with double sources, this makes in my case no sense, right?
Do you have a Idea why this happens?

If you want to test the live data, please let me know... Since my sources are only available for members, i created a Demo Account, just in case you want to test and review the data...

Regarding the case if there are doubled sources, like you described above, i'm very okay with how it is now... better no show a icon... so the editors can see that there is something wrong... i think it dont need a special warning message...

**Comment by Jefferson49** [comment]
> While I understood your explanation of the issue with double sources, this makes in my case no sense, right?
Do you have a Idea why this happens?

Your example showed several source citations below **one** INDI:OCCU tag. I can see 3 different source citations and the issue does not occur. 

However, the issue also appears if you have **several** INDI:OCCU tags within one INDI. In your screenshot, I can see 7 rows with INDI:OCCU tags. If a source citation in row 1 is identical to a source citation in row 7, the issue also occurs.

**Example screenshot:**
![same_source_citation](https://github.com/Jefferson49/RepositoryHierarchy/assets/81484983/c320e36d-13e0-4eaa-be73-ed88bb3b8b58)

**Comment by Jefferson49** [comment]
> Regarding the case if there are doubled sources, like you described above, i'm very okay with how it is now... better no show a icon... so the editors can see that there is something wrong... i think it dont need a special warning message...

The idea would be to show the icons without any warning messages. Only if you click "delete", a flash message could be shown with a text like: 
`"The selected source citation cannot be deleted, because the individual record contains several identical source citations (INDI:OCCU:SOUR:PAGE), and it cannot be de decided which one to delete. In this case, you need to manually remove the source citation."`

**Comment by HerzScheisse** [comment]
thanks for the explanation... now i got it... okay... i can live with that...

regarding your last message... yeah understood... but then why add the delete icon when its without function... I would keep it as it is... but you decide ;-)
